# Generated by Django 5.2.4 on 2025-07-19 08:48

from django.db import migrations


def create_assignment_template(apps, schema_editor):
    ResumeTemplate = apps.get_model('resume_builder', 'ResumeTemplate')

    # Remove old templates
    ResumeTemplate.objects.all().delete()

    # Create the assignment template
    ResumeTemplate.objects.create(
        name='Professional Modern',
        description='A modern, professional resume template with gradient header and asymmetric two-column layout. Perfect for tech professionals and creative industries.',
        format_type='ASSIGNMENT',
        version=1.0,
        is_active=True,
        thumbnail=None
    )


def reverse_assignment_template(apps, schema_editor):
    ResumeTemplate = apps.get_model('resume_builder', 'ResumeTemplate')
    ResumeTemplate.objects.filter(format_type='ASSIGNMENT').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_add_all_templates'),
    ]

    operations = [
        migrations.RunPython(create_assignment_template, reverse_assignment_template),
    ]
